server:
  port: 8081

spring:
  application:
    name: user-service
  datasource: # <-- Corrected indentation and placed directly under 'spring'
    url: jdbc:postgresql://localhost:5432/fitness_user_db
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect # <-- Corrected spelling

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

